// Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_ITEM_VO = 2;
const int HIVE_TYPE_ID_REVIEW_VO = 3;
const int HIVE_TYPE_ID_CATEGORY_VO = 4;
const int HIVE_TYPE_ID_DELIVERY_ADDRESS_VO = 5;
const int HIVE_TYPE_ID_ORDER_ITEM_VO = 6;
const int HIVE_TYPE_ID_ORDER_VO = 7;

// Box Names
const String BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const String BOX_NAME_ITEM_VO = "BOX_NAME_ITEM_VO";
const String BOX_NAME_CATEGORY_VO = "BOX_NAME_CATEGORY_VO";
const String BOX_NAME_ITEM_VO_FOR_CART = "BOX_NAME_ITEM_VO_FOR_CART";
const String BOX_NAME_ORDER_VO = "BOX_NAME_ORDER_VO";
